"""
One-time OAuth flow to generate a Google Ads refresh token.

Run this manually (not via the bridge) — it opens a browser tab and starts a
local callback server on port 8765 to catch the redirect code.

After completion, writes ~/.nobi/google-ads.yaml with all required fields.

Usage:
    python scripts/utils/google_ads_oauth.py
"""
import http.server
import json
import os
import threading
import urllib.parse
import webbrowser

SCOPES = ["https://www.googleapis.com/auth/adwords"]
REDIRECT_URI = "http://localhost:8765/callback"
YAML_PATH = os.path.expanduser("~/.nobi/google-ads.yaml")

# These are read from env or prompted interactively
CLIENT_ID     = os.getenv("GOOGLE_ADS_CLIENT_ID", "")
CLIENT_SECRET = os.getenv("GOOGLE_ADS_CLIENT_SECRET", "")
DEV_TOKEN     = os.getenv("GOOGLE_ADS_DEVELOPER_TOKEN", "")
LOGIN_CID     = os.getenv("GOOGLE_ADS_LOGIN_CUSTOMER_ID", "")

_callback_code = None
_server_done   = threading.Event()


class _CallbackHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        global _callback_code
        parsed = urllib.parse.urlparse(self.path)
        params = urllib.parse.parse_qs(parsed.query)
        _callback_code = params.get("code", [None])[0]
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b"Auth complete. You can close this tab.")
        _server_done.set()

    def log_message(self, format, *args):
        pass  # suppress access log noise


def _exchange_code(code, client_id, client_secret):
    import urllib.request
    data = urllib.parse.urlencode({
        "code": code,
        "client_id": client_id,
        "client_secret": client_secret,
        "redirect_uri": REDIRECT_URI,
        "grant_type": "authorization_code",
    }).encode()
    req = urllib.request.Request(
        "https://oauth2.googleapis.com/token",
        data=data,
        method="POST",
    )
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())


def run():
    global CLIENT_ID, CLIENT_SECRET, DEV_TOKEN, LOGIN_CID

    if not CLIENT_ID:
        CLIENT_ID = input("Google OAuth Client ID: ").strip()
    if not CLIENT_SECRET:
        CLIENT_SECRET = input("Google OAuth Client Secret: ").strip()
    if not DEV_TOKEN:
        DEV_TOKEN = input("Google Ads Developer Token: ").strip()
    if not LOGIN_CID:
        LOGIN_CID = input("Google Ads Manager Account (MCC) Customer ID: ").strip()

    # Build auth URL
    params = urllib.parse.urlencode({
        "client_id": CLIENT_ID,
        "redirect_uri": REDIRECT_URI,
        "response_type": "code",
        "scope": " ".join(SCOPES),
        "access_type": "offline",
        "prompt": "consent",
    })
    auth_url = f"https://accounts.google.com/o/oauth2/auth?{params}"

    # Start local callback server
    server = http.server.HTTPServer(("localhost", 8765), _CallbackHandler)
    t = threading.Thread(target=server.serve_forever)
    t.daemon = True
    t.start()

    print(f"\nOpening browser for Google OAuth...\n{auth_url}\n")
    webbrowser.open(auth_url)

    _server_done.wait(timeout=120)
    server.shutdown()

    if not _callback_code:
        print("ERROR: No auth code received (timed out?)")
        return

    print("Auth code received. Exchanging for tokens...")
    tokens = _exchange_code(_callback_code, CLIENT_ID, CLIENT_SECRET)
    refresh_token = tokens.get("refresh_token")
    if not refresh_token:
        print(f"ERROR: No refresh_token in response: {tokens}")
        return

    # Write google-ads.yaml
    os.makedirs(os.path.dirname(YAML_PATH), exist_ok=True)
    yaml_content = f"""# Google Ads API credentials — generated by google_ads_oauth.py
developer_token: {DEV_TOKEN}
client_id: {CLIENT_ID}
client_secret: {CLIENT_SECRET}
refresh_token: {refresh_token}
login_customer_id: {LOGIN_CID.replace('-', '')}
use_proto_plus: True
"""
    with open(YAML_PATH, "w") as f:
        f.write(yaml_content)

    print(f"\nCredentials written to {YAML_PATH}")
    print(f"Refresh token: {refresh_token}")


if __name__ == "__main__":
    run()
