// Generate per-route HTML for every blog post at build time.
//
// Why: Without this, the Cloudflare Pages deploy serves a single
// SPA shell (dist/index.html) for every URL. The shell carries the
// homepage <title>, og:* tags, and only Organization + WebSite
// JSON-LD - nothing article-specific. Crawlers that don't render
// JavaScript (Bing, AI training crawlers, social link previewers
// like LinkedIn / Twitter / Slack / Discord) see the homepage data
// when they fetch a blog URL. Even crawlers that render JS pay a
// freshness/reliability tax for waiting on hydration.
//
// What this does: after `vite build`, for every shipped .mdx in
// src/content/posts/, write dist/blog/<slug>/index.html with the
// article's title, meta description, og/twitter tags, canonical
// link, and Article + FAQPage + ItemList JSON-LD schemas injected
// into the head. The body remains the SPA shell (<div id="root">),
// so client-side hydration takes over from there - we're only
// fixing the initial HTML the crawler/preview-bot sees.
//
// Run via: node scripts/prerender-blog.js (chained from `build`).

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import vm from "vm";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT      = join(__dirname, "..");
const DIST      = join(ROOT, "dist");
const POSTS_DIR = join(ROOT, "src/content/posts");
const SHELL     = join(DIST, "index.html");
const BASE_URL  = "https://nobi.ai";

// Customer profiles for author bio. Mirrors src/content/authors.json
// at runtime; we read it for the schema author block but the page's
// visible byline is rendered client-side from the same source.
function loadAuthorsJson() {
  const path = join(ROOT, "src/content/authors.json");
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return {};
  }
}

// Pull the `export const meta = {...};` block out of an .mdx file
// and evaluate it in a sandboxed VM context. Safer than eval; the
// MDX files are checked into our repo so we trust the input but
// still want isolation.
function readMeta(mdxPath) {
  const content = readFileSync(mdxPath, "utf8");
  const match = content.match(/export const meta\s*=\s*(\{[\s\S]*?\n\s*\};)/);
  if (!match) return null;
  // The match includes the trailing `};` - strip it before evaluating.
  const body = match[1].replace(/;\s*$/, "");
  try {
    return vm.runInNewContext(`(${body})`, {}, { timeout: 1000 });
  } catch (e) {
    console.warn(`prerender: failed to parse meta in ${mdxPath}: ${e.message}`);
    return null;
  }
}

// Escape any character that would break out of an HTML attribute or
// element body. Used for content we inject into the head (title,
// description, og:* values).
function htmlEscape(s) {
  if (s === null || s === undefined) return "";
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// Resolve a heroImage value to an absolute URL. The frontmatter can
// carry either a relative `/media/...` path or a fully-qualified
// `https://storage.googleapis.com/...` URL; both are valid. og:image
// requires absolute.
function resolveImage(heroImage) {
  if (!heroImage) return `${BASE_URL}/og-image.png`;
  if (/^https?:\/\//i.test(heroImage)) return heroImage;
  return `${BASE_URL}${heroImage}`;
}

// Build the JSON-LD schema array for an article. Mirrors the runtime
// schema generated by src/pages/BlogPost.jsx so a JS-aware crawler
// and a JS-blind crawler see the same structured data.
function buildSchemas(meta, slug) {
  const article = {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": meta.title,
    "datePublished": meta.date,
    "dateModified": meta.lastUpdated || meta.publishedAt || meta.date,
    "image": resolveImage(meta.heroImage),
    "author": { "@type": "Person", "name": meta.author || "Nobi Team" },
    "publisher": { "@type": "Organization", "name": "Nobi", "url": "https://nobi.ai" },
    "mainEntityOfPage": { "@type": "WebPage", "@id": `${BASE_URL}/blog/${slug}` },
    "description": meta.description || meta.excerpt || "",
  };

  const schemas = [article];

  // FAQPage: real FAQs only, not vendor sections shaped like "1. Nobi".
  const faqItems = Array.isArray(meta.faqItems) ? meta.faqItems : [];
  const numberedVendor = /^\d+\.\s+/;
  const realFaqs = faqItems.filter(
    (i) => i && i.question && !numberedVendor.test(i.question)
  );
  if (realFaqs.length > 0) {
    schemas.push({
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": realFaqs.map((i) => ({
        "@type": "Question",
        "name": i.question,
        "acceptedAnswer": { "@type": "Answer", "text": i.answer },
      })),
    });
  }

  // ItemList: derived from numbered vendor entries in faqItems
  // (the assembler writes vendor sections as "1. Nobi", "2. Algolia"
  // questions). Required for "best of" SERP rich-result eligibility.
  const vendorEntries = faqItems
    .filter((i) => i && i.question && numberedVendor.test(i.question))
    .map((i, idx) => {
      const m = i.question.match(/^\d+\.\s+(.+)$/);
      const name = m ? m[1].trim() : null;
      if (!name) return null;
      return {
        "@type": "ListItem",
        "position": idx + 1,
        "name": name,
        "url": `${BASE_URL}/blog/${slug}#${name.toLowerCase().replace(/\s+/g, "-")}`,
      };
    })
    .filter(Boolean);
  if (vendorEntries.length >= 2) {
    schemas.push({
      "@context": "https://schema.org",
      "@type": "ItemList",
      "itemListElement": vendorEntries,
    });
  }

  return schemas;
}

// Build the head injection block for one article. Replaces the
// homepage's title/og/twitter/canonical with article-specific values
// and adds the per-article JSON-LD schemas.
function buildHeadInjection(meta, slug) {
  const url = `${BASE_URL}/blog/${slug}`;
  const title = meta.title ? `${meta.title} | Nobi` : "Nobi";
  const description = meta.description || meta.excerpt || "";
  const image = resolveImage(meta.heroImage);
  const schemas = buildSchemas(meta, slug);

  // The article's <title> and <meta name="description"> are written
  // separately (via the title/description placeholders that replace
  // the homepage versions). This block is everything else: canonical,
  // og:*, twitter:*, plus the JSON-LD schemas. Don't include title or
  // description here or they end up duplicated in the rendered HTML.
  const tags = [
    `<link rel="canonical" href="${htmlEscape(url)}">`,
    `<meta property="og:type" content="article">`,
    `<meta property="og:url" content="${htmlEscape(url)}">`,
    `<meta property="og:title" content="${htmlEscape(meta.title || "Nobi")}">`,
    `<meta property="og:description" content="${htmlEscape(description)}">`,
    `<meta property="og:image" content="${htmlEscape(image)}">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:title" content="${htmlEscape(meta.title || "Nobi")}">`,
    `<meta name="twitter:description" content="${htmlEscape(description)}">`,
    `<meta name="twitter:image" content="${htmlEscape(image)}">`,
  ];
  // Single script tag with id="page-schema" so useSEO finds and
  // updates the same element instead of creating a duplicate after
  // hydration. The runtime hook writes its array of schemas into the
  // same id; we mirror its shape here. If the array is just one
  // schema, useSEO writes a single object - we keep the array form
  // for consistency.
  if (schemas.length > 0) {
    tags.push(
      `<script type="application/ld+json" id="page-schema">${JSON.stringify(schemas)}</script>`
    );
  }
  return tags.join("\n    ");
}

// Strip the homepage's article-irrelevant head content from the SPA
// shell so the per-article values we inject aren't competing with
// stale homepage tags. We replace specific tag sets, not the whole
// head, so the Vite-injected scripts/styles stay intact.
function stripHomepageMeta(shell) {
  let out = shell;

  // Replace the static <title>.
  out = out.replace(
    /<title>[^<]*<\/title>/,
    "<!--__PRERENDER_TITLE__-->"
  );

  // Replace the homepage's <meta name="description">.
  out = out.replace(
    /<meta\s+name="description"\s+content="[^"]*"\s*\/?>\s*/,
    "<!--__PRERENDER_DESC__-->"
  );

  // Replace homepage og:* and twitter:* tags. The Vite shell emits
  // these statically pointing at "/" - swap them all.
  out = out.replace(
    /<meta\s+property="og:[^"]*"\s+content="[^"]*"\s*\/?>\s*/g,
    ""
  );
  out = out.replace(
    /<meta\s+name="twitter:[^"]*"\s+content="[^"]*"\s*\/?>\s*/g,
    ""
  );

  return out;
}

function prerenderOne(meta, slug, shell) {
  const headBlock = buildHeadInjection(meta, slug);
  let html = stripHomepageMeta(shell);

  // Drop the per-article block in place of the title/description
  // placeholders we just inserted. Keeps the rest of the head
  // (Vite scripts, GTM, MCP, theme color, fonts) untouched.
  html = html.replace(
    "<!--__PRERENDER_TITLE__-->",
    `<title>${htmlEscape(meta.title ? `${meta.title} | Nobi` : "Nobi")}</title>`
  );
  html = html.replace(
    "<!--__PRERENDER_DESC__-->",
    `<meta name="description" content="${htmlEscape(meta.description || meta.excerpt || "")}">\n    ${headBlock}`
  );

  // Write BOTH dist/blog/<slug>.html AND dist/blog/<slug>/index.html
  // so the prerendered file is served regardless of trailing-slash
  // form. Cloudflare Pages (and vite preview) match the slugless URL
  // /blog/<slug> against <slug>.html when that file exists; the
  // trailing-slash form /blog/<slug>/ matches the index.html under
  // the directory. Without both, the no-slash URL (which the sitemap
  // and internal links use) falls through to the SPA shell.
  const dirPath = join(DIST, "blog", slug);
  mkdirSync(dirPath, { recursive: true });
  writeFileSync(join(dirPath, "index.html"), html);
  // Flat file alongside the directory; the slugless URL resolves to
  // <slug>.html. mkdirSync above guarantees dist/blog/ exists.
  writeFileSync(join(DIST, "blog", `${slug}.html`), html);
}

function main() {
  if (!existsSync(SHELL)) {
    console.warn(
      `prerender: dist/index.html not found - run 'vite build' first. Skipping.`
    );
    return;
  }
  const shell = readFileSync(SHELL, "utf8");

  const today = new Date().toISOString().slice(0, 10);
  const files = readdirSync(POSTS_DIR).filter((f) => f.endsWith(".mdx"));
  let written = 0;
  let skipped = 0;

  for (const file of files) {
    const meta = readMeta(join(POSTS_DIR, file));
    if (!meta || !meta.slug) {
      skipped++;
      continue;
    }
    if (meta.draft === true) {
      skipped++;
      continue;
    }
    // Skip future-dated posts (consistent with the sitemap).
    const publishDate = meta.publishedAt || meta.date;
    if (publishDate && publishDate > today) {
      skipped++;
      continue;
    }
    try {
      prerenderOne(meta, meta.slug, shell);
      written++;
    } catch (e) {
      console.warn(`prerender: failed for ${meta.slug}: ${e.message}`);
      skipped++;
    }
  }

  console.log(`✓ prerender — ${written} blog posts (${skipped} skipped)`);
}

main();
